name: submodule-updates

on:
  #schedule:
  # * is a special character in YAML so you have to quote this string
  # https://crontab.guru/#5_*_*_*_*
  #  - cron: '5 * * * *'
  - push


jobs:

  check-submodules:

    name: check-submodules-job

    runs-on: ubuntu-latest

    env:

      REPO__CHECKOUT_PATH: 'gharial'
      REPO__SUBMODULE_PATH: 'gharial/dependabot_sub_a'
      REPO__SUBMODULE_SHA1: ''

      SUBMODULE_REPO__CHECKOUT_PATH: 'dependabot_sub_a'
      SUBMODULE_REPO__SHA1: ''
      SUBMODULE_REPO__CHECK_DIR: 'interesting_dir'

      SUBDMODULE_REPO__HAS_NEW_CHANGES: 'no'
      SUBDMODULE_REPO__HAS_NEW_CHANGES_IN_CHECK_DIR: 'no'



    steps:

      # checkout our repo
      - name: check out repo
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          path: ./${{ env.REPO__CHECKOUT_PATH }}
          fetch-depth: 1 # we only need a shallow clone to get the submodule revision

      # get the revision of the submodule in our repo
      - name: get head rev of submodule in our repo
        run:  |
          cd ${{ env.REPO__SUBMODULE_PATH }}
          echo "repo->submodule: ${PWD}"
          echo "REPO__SUBMODULE_SHA1=$(git rev-parse HEAD)"  >> $GITHUB_ENV
          echo "REPO__SUBMODULE_SHA1=$REPO__SUBMODULE_SHA1"
          cd -

      # checkout the submodule repo
      - name: checkout submodule repo
        uses: actions/checkout@v2
        with:
          repository: coolbreeze413/dependabot_sub_a
          path: ./${{ env.SUBMODULE_REPO__CHECKOUT_PATH }}
          fetch-depth: 0 # we need all history, not a shallow clone for checking changes

      # get the revision of the submodule repo's HEAD
      - name: get head rev of the submodule repo
        run:  |
          cd ${{ env.SUBMODULE_REPO__CHECKOUT_PATH }}
          echo "submodule's repo : ${PWD}"
          echo "SUBMODULE_REPO__SHA1=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "SUBMODULE_REPO__SHA1=$SUBMODULE_REPO__SHA1"
          cd -

      # are there any differences between submodule repo HEAD and our repo submodule rev
      - name: check if submodule repo has new changes
        if:  ${{ env.SUBMODULE_REPO__SHA1 }} != ${{ env.REPO__SUBMODULE_SHA1 }}
        run: |
          echo "SUBDMODULE_REPO__HAS_NEW_CHANGES='yes'" >> $GITHUB_ENV
          echo "SUBDMODULE_REPO__HAS_NEW_CHANGES=$SUBDMODULE_REPO__HAS_NEW_CHANGES"


      # are there differences in a specific dir in the submodule repo
      - name: check if there are changes in the specific dir that we are looking for
        if: ${{ env.SUBDMODULE_REPO__HAS_NEW_CHANGES }} == 'yes'
        run: |
          cd ${{ env.SUBMODULE_REPO__CHECKOUT_PATH }}
          echo "submodule's repo : ${PWD}"
          git log --oneline
          CHANGES=git diff --name-only ${{ env.REPO__SUBMODULE_SHA1 }}..${{ env.SUBMODULE_REPO__SHA1 }}
          echo "changes:"
          echo "$CHANGES"
          echo "SUBDMODULE_REPO__HAS_NEW_CHANGES_IN_CHECK_DIR=$(git diff --quiet ${{ env.REPO__SUBMODULE_SHA1 }}..${{ env.SUBMODULE_REPO__SHA1 }} -- ${{ env.SUBMODULE_REPO__CHECK_DIR }} || echo yes)" >> $GITHUB_ENV
          echo "SUBDMODULE_REPO__HAS_NEW_CHANGES_IN_CHECK_DIR=$SUBDMODULE_REPO__HAS_NEW_CHANGES_IN_CHECK_DIR"

          



