name: test-json-array

on:
  push:
    branches:
      - 'master'

jobs:
  
  test-json-array-job:

    name: test-json-array-job
    runs-on: ubuntu-latest

    env:
      MULTIPLE_ITEMS_JSON: '["item_a", "item_b", "item_c", "item with spaces"]'
      au_device_package_pattern: testarray/PACKAGEPREFIX_*_en.tar.gz

    steps:

      - name: list json items
        shell: bash
        run:  |
          items=$(echo '${{ env.MULTIPLE_ITEMS_JSON }}' | jq -c -r '.[]')
          for item in "${items[@]}"; do
            echo "$item"
          done

      - name: check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1


      - name: bash array items
        shell: bash
        run:  |
          WHICHTAG="v2.8.0"
          au_device_package_pattern="testarray/PACKAGEPREFIX_*_en.tar.gz"
          DEVICE_PACKAGES_ARRAY=($(ls ${{ env.au_device_package_pattern }}))
          NUM_FILES=${#DEVICE_PACKAGES_ARRAY[*]}
          echo ">>> found : ${NUM_FILES} ${au_device_package_pattern} files"

          echo
          echo "array:"
          echo "${DEVICE_PACKAGES_ARRAY[*]}"
          echo
          echo


          # i=0
          # while [ $i -lt ${NUM_FILES} ] ; do
          #   echo $i
          #   DEVICE_PACKAGE_CURRENT="${DEVICE_PACKAGES_ARRAY[$i]}"
          #   echo "${DEVICE_PACKAGE_CURRENT}"
          #   DEVICE_PACKAGE_CONTINUOUS=$(echo "${DEVICE_PACKAGE_CURRENT}" | sed -e "s/${WHICHTAG}/continuous/")
          #   echo "${DEVICE_PACKAGE_CONTINUOUS}"
          #   let i++
          # done
          i=0
          for DEVICE_PACKAGE_CURRENT in "${DEVICE_PACKAGES_ARRAY[@]}"; do
            echo "1"
            echo $i
            echo "${DEVICE_PACKAGE_CURRENT}"
            DEVICE_PACKAGE_CONTINUOUS=$(echo "${DEVICE_PACKAGE_CURRENT}" | sed -e "s/${WHICHTAG}/continuous/")
            echo "${DEVICE_PACKAGE_CONTINUOUS}"
            echo "2"
            i=i+1
            echo "3"
          done

