name: workflow-dispatch-workflow

on:
  workflow_dispatch:
    branches:
      - 'master'

jobs:

  simple-dispatch-job:
    name: simple-dispatch-job
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
